### ISSUE TITLE
python-syntax-count-quotes is not defined

### ISSUE THREAD

**Issue by edcrypt** [superbobry/io-mode#11]
Seems like io-mode is trying to use an old function from python-mode, or from a version/implementation of python-mode other than the one that comes with emacs25.

**Comment by superbobry** [comment]
Hi, I don't actively use Io anymore, so I don't use the mode myself, but I'd welcome a patch replacing `python-syntax-count-quotes` with a more modern alternative.

**Comment by syohex** [comment]
I have sent PR #12. It removes python-mode dependency and fixes byte-compile error.
